markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
pygments        : true
exclude         : [branding]
contact         : "oss2014@nceas.ucsb.edu"
github_url      : "https://github.com/NCEAS/training"
irc_url         : "http://webchat.nceas.ucsb.edu/?channels=oss"
twitter_name    : "#oss2014"
twitter_url     : "https://twitter.com/hashtag/oss2014"
